### ISSUE TITLE
Why all the optionals?

### ISSUE THREAD

**Issue by rkgibson2** [pltlg/FCMNN#2]
Why do you have all the caches as optional? They are all initialized in the input, so I don't see where they could become optional? All it does is create lots of force unwrappings.

Similarly, I'm unclear why the `weights` parameter of init is nil. Won't line 23 crash if `weights` is nil?

**Comment by pletl** [comment]
Thank you for the remark, you can make a pull req if you have time. If you do please correct the shift function. The offset calc should use modulo.
